language: php

php:
  - 7
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - hhvm

before_script:
  - composer require satooshi/php-coveralls:dev-master
  - composer update

script:
  - mkdir -p build/logs
  - phpunit --colors --coverage-clover build/logs/clover.xml ./tests

after_script:
  - php vendor/bin/coveralls -v
